services:
  spa:
    container_name: simple_finances_spa_prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    image: simple-finances-spa:prod
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${TRAEFIK_APP_NAME}.rule=Host(`${SPA_DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_APP_NAME}.tls=true"
      - "traefik.http.routers.${TRAEFIK_APP_NAME}.tls.certresolver=le"
      - "traefik.http.services.${TRAEFIK_APP_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${TRAEFIK_APP_NAME}-legacy.rule=Host(`${SPA_LEGACY_DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_APP_NAME}-legacy.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_APP_NAME}-legacy.tls=true"
      - "traefik.http.routers.${TRAEFIK_APP_NAME}-legacy.tls.certresolver=le"
      - "traefik.http.routers.${TRAEFIK_APP_NAME}-legacy.middlewares=${TRAEFIK_APP_NAME}-legacy-redirect"
      - "traefik.http.routers.${TRAEFIK_APP_NAME}-legacy.service=noop@internal"
      - "traefik.http.middlewares.${TRAEFIK_APP_NAME}-legacy-redirect.redirectregex.regex=^https?://${SPA_LEGACY_DOMAIN}/(.*)"
      - "traefik.http.middlewares.${TRAEFIK_APP_NAME}-legacy-redirect.redirectregex.replacement=https://${SPA_DOMAIN}/$${1}"
      - "traefik.http.middlewares.${TRAEFIK_APP_NAME}-legacy-redirect.redirectregex.permanent=true"
    networks:
      - proxy

networks:
  proxy:
    external: true
