import { definePreset } from '@primeuix/themes';
import Aura from '@primeuix/themes/aura';
import type { PrimeVueLocaleOptions } from 'primevue/config';

export const appPreset = definePreset(Aura, {
    semantic: {
        primary: {
            50: '{blue.50}',
            100: '{blue.100}',
            200: '{blue.200}',
            300: '{blue.300}',
            400: '{blue.400}',
            500: '{blue.500}',
            600: '{blue.600}',
            700: '{blue.700}',
            800: '{blue.800}',
            900: '{blue.900}',
            950: '{blue.950}',
        },
        formField: {
            borderRadius: '0.75rem',
            paddingX: '0.875rem',
            paddingY: '0.625rem',
        },
        focusRing: {
            width: '2px',
            offset: '2px',
        },
    },
});

export const spanishLocale: PrimeVueLocaleOptions = {
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
    dayNames: ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'],
    dayNamesShort: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
    dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
    monthNames: [
        'enero',
        'febrero',
        'marzo',
        'abril',
        'mayo',
        'junio',
        'julio',
        'agosto',
        'septiembre',
        'octubre',
        'noviembre',
        'diciembre',
    ],
    monthNamesShort: [
        'ene',
        'feb',
        'mar',
        'abr',
        'may',
        'jun',
        'jul',
        'ago',
        'sep',
        'oct',
        'nov',
        'dic',
    ],
    firstDayOfWeek: 0,
    dateFormat: 'yy-mm-dd',
    today: 'Hoy',
    clear: 'Limpiar',
    apply: 'Aplicar',
    cancel: 'Cancelar',
    accept: 'Aceptar',
    reject: 'Cancelar',
    chooseDate: 'Elegir fecha',
    chooseMonth: 'Elegir mes',
    chooseYear: 'Elegir año',
    prevMonth: 'Mes anterior',
    nextMonth: 'Mes siguiente',
    prevYear: 'Año anterior',
    nextYear: 'Año siguiente',
    prevDecade: 'Década anterior',
    nextDecade: 'Década siguiente',
    prevHour: 'Hora anterior',
    nextHour: 'Hora siguiente',
    prevMinute: 'Minuto anterior',
    nextMinute: 'Minuto siguiente',
    prevSecond: 'Segundo anterior',
    nextSecond: 'Segundo siguiente',
    emptyMessage: 'No hay resultados disponibles.',
    emptyFilterMessage: 'No hay resultados disponibles.',
    emptySearchMessage: 'No se encontraron resultados.',
    searchMessage: '{0} resultados disponibles',
    selectionMessage: '{0} elementos seleccionados',
    emptySelectionMessage: 'Sin selección',
    aria: {
        close: 'Cerrar',
        previous: 'Anterior',
        next: 'Siguiente',
        navigation: 'Navegación',
        selectRow: 'Seleccionar fila',
        unselectRow: 'Deseleccionar fila',
        expandRow: 'Expandir fila',
        collapseRow: 'Contraer fila',
        selectAll: 'Seleccionar todo',
        unselectAll: 'Deseleccionar todo',
    },
};
