import { definePreset } from '@primeuix/themes';
import Aura from '@primeuix/themes/aura';
import type { PrimeVueLocaleOptions } from 'primevue/config';

export const appPreset = definePreset(Aura, {
    primitive: {
        borderRadius: {
            none: '0',
            xs: '2px',
            sm: 'var(--app-radius-control)',
            md: 'var(--app-radius-control)',
            lg: 'var(--app-radius-overlay)',
            xl: 'var(--app-radius-overlay)',
        },
    },
    semantic: {
        primary: {
            50: '#eff8f9',
            100: '#d8eef1',
            200: '#b3dfe5',
            300: '#7dd3e2',
            400: '#49b2c3',
            500: '#238a9e',
            600: '#0e6474',
            700: '#0b5361',
            800: '#08424d',
            900: '#082f38',
            950: '#051e25',
            color: 'var(--app-color-primary)',
            contrastColor: 'var(--app-color-primary-foreground)',
            hoverColor: 'var(--app-color-primary-hover)',
            activeColor: 'var(--app-color-primary-active)',
        },
        formField: {
            borderRadius: 'var(--app-radius-control)',
            fontSize: '1rem',
            paddingX: '0.875rem',
            paddingY: '0.625rem',
            background: 'var(--app-color-input-bg)',
            color: 'var(--app-color-input-text)',
            borderColor: 'var(--app-color-input-border)',
            hoverBorderColor: 'var(--app-color-primary)',
            invalidBorderColor: 'var(--app-color-danger)',
            placeholderColor: 'var(--app-color-input-placeholder)',
            focusRing: {
                width: '2px',
                style: 'solid',
                color: 'var(--app-color-focus-ring)',
                offset: '2px',
            },
        },
        text: {
            color: 'var(--app-color-text)',
            hoverColor: 'var(--app-color-text)',
            mutedColor: 'var(--app-color-text-muted)',
            hoverMutedColor: 'var(--app-color-text)',
        },
        content: {
            background: 'var(--app-color-surface)',
            hoverBackground: 'var(--app-color-surface-muted)',
            borderColor: 'var(--app-color-border)',
            color: 'var(--app-color-text)',
            hoverColor: 'var(--app-color-text)',
        },
        highlight: {
            background:
                'color-mix(in srgb, var(--app-color-primary) 12%, var(--app-color-surface))',
            focusBackground:
                'color-mix(in srgb, var(--app-color-primary) 20%, var(--app-color-surface))',
            color: 'var(--app-color-primary)',
            focusColor: 'var(--app-color-primary)',
        },
        overlay: {
            select: {
                background: 'var(--app-color-surface)',
                color: 'var(--app-color-text)',
                borderColor: 'var(--app-color-border)',
                borderRadius: 'var(--app-radius-control)',
            },
            modal: {
                background: 'var(--app-color-surface)',
                color: 'var(--app-color-text)',
                borderColor: 'var(--app-color-border)',
                borderRadius: 'var(--app-radius-overlay)',
            },
        },
        focusRing: {
            width: '2px',
            offset: '2px',
            color: 'var(--app-color-focus-ring)',
        },
    },
    components: {
        toggleswitch: {
            root: { borderRadius: 'var(--app-radius-control)' },
            handle: { borderRadius: '2px' },
        },
        button: {
            root: {
                danger: {
                    background: 'var(--app-color-danger)',
                    hoverBackground: 'var(--app-color-danger-hover)',
                    activeBackground: 'var(--app-color-danger-hover)',
                    borderColor: 'var(--app-color-danger)',
                    hoverBorderColor: 'var(--app-color-danger-hover)',
                    activeBorderColor: 'var(--app-color-danger-hover)',
                    color: 'var(--app-color-danger-foreground)',
                    hoverColor: 'var(--app-color-danger-foreground)',
                    activeColor: 'var(--app-color-danger-foreground)',
                },
                secondary: {
                    background: 'var(--app-color-secondary)',
                    hoverBackground: 'var(--app-color-secondary-hover)',
                    activeBackground: 'var(--app-color-secondary-hover)',
                    borderColor: 'var(--app-color-secondary)',
                    hoverBorderColor: 'var(--app-color-secondary-hover)',
                    activeBorderColor: 'var(--app-color-secondary-hover)',
                    color: 'var(--app-color-secondary-foreground)',
                    hoverColor: 'var(--app-color-secondary-foreground)',
                    activeColor: 'var(--app-color-secondary-foreground)',
                },
            },
            text: {
                secondary: {
                    color: 'var(--app-color-text-muted)',
                    hoverBackground: 'var(--app-color-surface-muted)',
                    activeBackground: 'var(--app-color-surface-muted)',
                },
            },
        },
    },
});

export const spanishLocale: PrimeVueLocaleOptions = {
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
    dayNames: ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'],
    dayNamesShort: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
    dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
    monthNames: [
        'enero',
        'febrero',
        'marzo',
        'abril',
        'mayo',
        'junio',
        'julio',
        'agosto',
        'septiembre',
        'octubre',
        'noviembre',
        'diciembre',
    ],
    monthNamesShort: [
        'ene',
        'feb',
        'mar',
        'abr',
        'may',
        'jun',
        'jul',
        'ago',
        'sep',
        'oct',
        'nov',
        'dic',
    ],
    firstDayOfWeek: 0,
    dateFormat: 'yy-mm-dd',
    today: 'Hoy',
    clear: 'Limpiar',
    apply: 'Aplicar',
    cancel: 'Cancelar',
    accept: 'Aceptar',
    reject: 'Cancelar',
    chooseDate: 'Elegir fecha',
    chooseMonth: 'Elegir mes',
    chooseYear: 'Elegir año',
    prevMonth: 'Mes anterior',
    nextMonth: 'Mes siguiente',
    prevYear: 'Año anterior',
    nextYear: 'Año siguiente',
    prevDecade: 'Década anterior',
    nextDecade: 'Década siguiente',
    prevHour: 'Hora anterior',
    nextHour: 'Hora siguiente',
    prevMinute: 'Minuto anterior',
    nextMinute: 'Minuto siguiente',
    prevSecond: 'Segundo anterior',
    nextSecond: 'Segundo siguiente',
    emptyMessage: 'No hay resultados disponibles.',
    emptyFilterMessage: 'No hay resultados disponibles.',
    emptySearchMessage: 'No se encontraron resultados.',
    searchMessage: '{0} resultados disponibles',
    selectionMessage: '{0} elementos seleccionados',
    emptySelectionMessage: 'Sin selección',
    aria: {
        close: 'Cerrar',
        previous: 'Anterior',
        next: 'Siguiente',
        navigation: 'Navegación',
        selectRow: 'Seleccionar fila',
        unselectRow: 'Deseleccionar fila',
        expandRow: 'Expandir fila',
        collapseRow: 'Contraer fila',
        selectAll: 'Seleccionar todo',
        unselectAll: 'Deseleccionar todo',
    },
};
